"""cascade dottaglink 

Revision ID: 55e8ca2e48b2
Revises: 66ddde949148
Create Date: 2026-09-10 13:24:14.895709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '55e8ca2e48b2'
down_revision: Union[str, Sequence[str], None] = '66ddde949148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dottaglink_user_id_fkey'), 'dottaglink', type_='foreignkey')
    op.create_foreign_key(None, 'dottaglink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dottaglink', type_='foreignkey')
    op.create_foreign_key(op.f('dottaglink_user_id_fkey'), 'dottaglink', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
