"""add cascade delete

Revision ID: 66ddde949148
Revises: 7c5243ee9553
Create Date: 2026-09-10 13:18:15.250643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '66ddde949148'
down_revision: Union[str, Sequence[str], None] = '7c5243ee9553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.drop_constraint(op.f('tag_user_id_fkey'), 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key(op.f('tag_user_id_fkey'), 'tag', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.alter_column('tag', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
