"""fix replytodot cascade

Revision ID: 6d2cc087a624
Revises: b9472d640597
Create Date: 2026-09-10 13:33:53.965074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '6d2cc087a624'
down_revision: Union[str, Sequence[str], None] = 'b9472d640597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replytodot', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('replytodot_user_id_fkey'), 'replytodot', type_='foreignkey')
    op.create_foreign_key(None, 'replytodot', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replytodot', type_='foreignkey')
    op.create_foreign_key(op.f('replytodot_user_id_fkey'), 'replytodot', 'user', ['user_id'], ['id'])
    op.alter_column('replytodot', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
