"""fix diaryentry cascade

Revision ID: 8dd4bb5599bc
Revises: 6d2cc087a624
Create Date: 2026-09-10 13:38:01.366647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8dd4bb5599bc'
down_revision: Union[str, Sequence[str], None] = '6d2cc087a624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
