"""initial

Revision ID: aea296b9aa37
Revises: 
Create Date: 2026-09-10 12:52:11.674272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'aea296b9aa37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('diary_user_id_fkey'), 'diary', type_='foreignkey')
    op.create_foreign_key(None, 'diary', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dottaglink', 'dot', ['dot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dottaglink', type_='foreignkey')
    op.drop_constraint(None, 'diary', type_='foreignkey')
    op.create_foreign_key(op.f('diary_user_id_fkey'), 'diary', 'user', ['user_id'], ['id'])
    op.alter_column('diary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
