"""fix diaryentrytaglink cascade 

Revision ID: b9472d640597
Revises: 55e8ca2e48b2
Create Date: 2026-09-10 13:28:49.549994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b9472d640597'
down_revision: Union[str, Sequence[str], None] = '55e8ca2e48b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diaryentrytaglink_user_id_fkey'), 'diaryentrytaglink', type_='foreignkey')
    op.create_foreign_key(None, 'diaryentrytaglink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diaryentrytaglink', type_='foreignkey')
    op.create_foreign_key(op.f('diaryentrytaglink_user_id_fkey'), 'diaryentrytaglink', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
