"""fix diaryentry cascade2

Revision ID: ff8f49d4b7a0
Revises: 8dd4bb5599bc
Create Date: 2026-09-10 13:38:30.492729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ff8f49d4b7a0'
down_revision: Union[str, Sequence[str], None] = '8dd4bb5599bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaryentry', 'diary_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('diaryentry_diary_id_fkey'), 'diaryentry', type_='foreignkey')
    op.create_foreign_key(None, 'diaryentry', 'diary', ['diary_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diaryentry', type_='foreignkey')
    op.create_foreign_key(op.f('diaryentry_diary_id_fkey'), 'diaryentry', 'diary', ['diary_id'], ['id'])
    op.alter_column('diaryentry', 'diary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
